### ISSUE TITLE
Update PBIS connector_rpms links

### ISSUE THREAD

**Issue by confusdcodr** [plus3it/join-domain-formula#148]
The links to download pbis are all inaccurate. The links can be found here - https://github.com/plus3it/join-domain-formula/blob/master/join-domain/elx/pbis/map.jinja#L20-L22

Currently, when you attempt to visit one of the links, you get a "No Such Bucket" error

**Comment by YakDriver** [comment]
It looks like they can be downloaded on GitHub Releases but they need to be renamed: 

For example, https://github.com/BeyondTrust/pbis-open/releases/download/8.5.3/pbis-open-8.5.3.293.linux.x86_64.rpm.sh needs to `.sh` chopped.

**Comment by ferricoxide** [comment]
Unless we want to act as a republisher for the world, I would probalby _not_ try to "fix" those links to point to a valid bucket-URL.
