### ISSUE TITLE
Add salt formula syntax validation to Travis CI tests

### ISSUE THREAD

**Issue by lorengordon** [plus3it/join-domain-formula#18]
Refs:
- http://lambdaops.com/automation/travis/travis%20ci/configuration%20management/continuous%20integration/salt/chef/saltstack/salt%20stack/2014/01/29/travis-for-salt-states/
- https://groups.google.com/d/msg/salt-users/M4YxlFOlw7U/mbOCp0AUCgAJ
- https://09663951122791824653.googlegroups.com/attach/a1440a782b399/travis.yml?part=0.0.1&view=1&vt=ANaJVrE4L5E7W7Cpm-72sjE84rUs0VADqIxmB1SffxnOYHUfuhLYm_jN-8vo3UaOPhOxqFYeZSzZfBOuRK142sU7ywQ9kqg4DQzVEXnU0mldnuJjTMDBzIc

**Comment by ferricoxide** [comment]
So, *just* syntax checks, not functionality checks (since, while the software installs and config steps would succeed, the actual join-op would always fail)?

**Comment by lorengordon** [comment]
Exactly. For now, anyway. More sophisticated tests can be tackled later. We'd have to mock the domain join, or support a "test" flag on the state to skip that step.

**Comment by ferricoxide** [comment]
Cool. Didn't want to go running down the rabbit-hole. =)

**Comment by ferricoxide** [comment]
Do we have any idea what distro the Travis instances are running on? Or will that be immaterial for basic syntax checks (i.e., "do the Travis instances grok RPM ...since one of the states uses RPMs").

**Comment by lorengordon** [comment]
Shouldn't matter for the syntax check. Nothing gets installed.

**Comment by ferricoxide** [comment]
K. Some of the URLs seemed to be talking about executing blocks as a method for verifying them.

**Comment by lorengordon** [comment]
Well, I selected those links because they only talk about syntax validation, and the code they provide only executes syntax validation. Can you be more specific about the exact text or code that you have the question about?

**Comment by lorengordon** [comment]
Closed by #70
