### ISSUE TITLE
Linux/PBIS: Add option to upgrade client-agent version

### ISSUE THREAD

**Issue by ferricoxide** [plus3it/join-domain-formula#27]
For lifecycle usage, need to add the capability of upgrading the Linux AD client software's installed version. PBIS will, by default, do an upgrade-in-place if the installer is simply invoked with `pbis-open-<VERSION>.linux.<ARCH>.rpm.sh -- --dont-join --legacy install`

**Comment by ferricoxide** [comment]
@lorengordon you got bit by this one, recently, correct? You updated the pillar data and associated methods such that this issue should be closeable, correct?

**Comment by lorengordon** [comment]
Yes, closing. Simply referencing newer versions of the pbis rpms in the `connector_rpms` pillar key will cause the states to upgrade pbis using yum.
