### ISSUE TITLE
join.sh: Password hash decryption-method is not FIPS-compatible

### ISSUE THREAD

**Issue by ferricoxide** [plus3it/join-domain-formula#72]
CIS/STIG-hardened EL7 host will be FIPS enabled. When running `join-domain-formula/join-domain/elx/pbis/files/join.sh` in interactive diagnostic mode, script throws the following error in the decrypt operation:
~~~
PWCLEAR=$(echo "${PWCRYPT}" | openssl enc -aes-256-ecb -a -d -salt -pass pass:"${PWUNLOCK}")
~~~
produces:
~~~
140407787075488:error:060800A3:digital envelope routines:EVP_DigestInit_ex:disabled for fips:digest.c:251:
140407787075488:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:evp_enc.c:604:
~~~
Need to find alternate (FIPS-compatible) method for passing join-user's credentials into the Salt-run.

**Comment by ferricoxide** [comment]
Per Red Hat [Solution Document #176633](https://access.redhat.com/solutions/176633), current method fails due to default digest method being (the non FIPS-compatible) MD5. Will need to update methods for creating and decrypting hash-string. Change the `join.sh` helper script's `PWdecrypt` function to:
~~~
local PWCLEAR=$(echo "${PWCRYPT}" | openssl aes-256-cbc -md sha256 -a -d \
                   -salt -pass pass:"${PWUNLOCK}")
~~~

**Comment by lorengordon** [comment]
Maybe make the cipher methods pillar items, since they need to be the same for the encrypt and decrypt routines?

**Comment by ferricoxide** [comment]
Worth considering, but, really shouldn't be using MD5 even if the system isn't FIPSed. Since `-md sha256` is portable, not inclined to more-broadly reorganize things until I can get the basic functionality of all the deadline pieces sorted.

To borrow a phrase, "put a pin in it" (along with better-organizing the combined pillar as a whole).
