### ISSUE TITLE
Protect Against Corruption From (Oversized) Domain-Enumerations

### ISSUE THREAD

**Issue by ferricoxide** [plus3it/join-domain-formula#89]
See [PBIS issue 34](/BeyondTrust/pbis-open/issues/34)

**Comment by lorengordon** [comment]
When I investigated this at the time, iirc, that was the default setting.

**Comment by ferricoxide** [comment]
Closing: this issue was opened in support of PBIS-based integration. PBIS was deprecated by the vendor in CY2019Q4 (see the About section of the [vendor's GitHub project](https://github.com/BeyondTrust/pbis-open)).
